version: 2
jobs:
  build:
    working_directory: ~/body-parser-graphql
    docker:
      - image: circleci/node:latest@sha256:de36894a21213e95a15ae412981429bb94c2b94710ccc161f628a31e92bb44ca
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: release
          command: yarn semantic-release || true
      - store_artifacts:
          path: coverage
          prefix: coverage